spring.application.name=aquisicaocredito

spring.datasource.url=jdbc:postgresql://localhost:5432/aquisicaocredito
spring.datasource.username=aquisicaocredito
spring.datasource.password=aquisicaocredito
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.open-in-view=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

produtocredito.api.base-url=https://desafio-credito-sicredi.wiremockapi.cloud