CREATE TABLE titulo_credito (
    id_operacao_credito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_associado BIGINT NOT NULL,
    valor_operacao NUMERIC(19, 2) NOT NULL,
    segmento VARCHAR(4) NOT NULL,
    codigo_produto_credito VARCHAR(4) NOT NULL,
    codigo_conta VARCHAR(10) NOT NULL,
    area_beneficiada_ha NUMERIC(19, 2),
    data_hora_contratacao TIMESTAMP NOT NULL
);
