CREATE TABLE socio_beneficiario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_operacao_credito BIGINT NOT NULL REFERENCES titulo_credito (id_operacao_credito),
    id_associado BIGINT NOT NULL
);
